compliance updated in prestashop 1.6
hps/heartland-prestashop-plugin pull request #19
Opened 2024-03-20 09:48 UTC by tsysamit

compliance updated in prestashop 1.6

2024-03-21 08:14 UTC, mayur-vachchewar requested changes

2024-03-21 08:14 UTC, mayur-vachchewar commented on modules/securesubmitpayment/payment.tpl
> +		<!--<button type="submit" class="securesubmit-submit-button">{l s='Submit Payment' mod='securesubmitpayment'}</button>-->
Please remove this commented line.

2024-03-24 17:51 UTC, MSmedal approved these changes
Looks great! Just a couple of minor clean-up items.

2024-03-24 17:51 UTC, MSmedal commented on modules/securesubmitpayment/assets/js/securesubmit.js
> +      //alert ('[' + response.token_value + ']');
```suggestion
```

2024-03-24 17:51 UTC, MSmedal commented on modules/securesubmitpayment/assets/js/securesubmit.js
> +
```suggestion
```

2024-03-26 13:25 UTC, tsysamit commented
@MSmedal I have updated the code as per your comments. Please check and approve

2024-03-26 14:56 UTC, MSmedal approved these changes

2024-04-11 12:24 UTC, merged